before_install:
  - curl -L https://raw.githubusercontent.com/krlmlr/texlive-squashfs/master/out/texlive.tar.xz | tar xJC ~

install:
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  - tlmgr install exam
script:
- mkdir _build
- pdflatex -output-directory _build -interaction=nonstopmode -halt-on-error tex/question_algebra.tex
deploy:
  provider: releases
  api_key:
    secure: [YOUR KEY]
  file:
  - _build/question_algebra.pdf
  skip_cleanup: true
  on:
    tags: true
